Изменение порядка контейнеров
bmstu-iu9/ptp2021-4-chat pull request #25
Opened 2021-07-19 14:31 UTC by pollykon

2021-07-19 15:03 UTC, boomb0om commented
Не совсем то сделала. Нужно, чтобы порядок менялся только на мобильных устройствах, а у тебя порядок меняется везде. Попробуй в css добавить медиа-запрос на ширину экрана, и в этом медиа запросе уже менять порядок (вроде просто надо добавить свойство order)

2021-07-19 16:30 UTC, boomb0om commented on src/styles/login.css
> +    }
ты тут на общий класс .simple-window это свойство применила (оба окошка имеют этот класс), а нужно только на окно с логином

2021-07-19 16:30 UTC, boomb0om requested changes

2021-07-19 16:30 UTC, boomb0om commented on src/styles/login.css
> +        order: 2;
ты тут на общий класс .simple-window это свойство применила (оба окошка имеют этот класс), а нужно только на окно с логином

2021-07-19 18:15 UTC, boomb0om requested changes

2021-07-19 18:15 UTC, boomb0om commented on src/styles/login.css
> +        display: flex;
У .main вроде стоит бутстраповский класс .container-flex, которорый уже применяет flex. Без этого не работает чтоль?

2021-07-19 18:15 UTC, boomb0om commented on src/styles/login.css
> +        order: 1;
Опять применяешь order ко всем окнам (это общий для всех класс)

2021-07-21 17:34 UTC, Postlog requested changes

2021-07-21 17:34 UTC, Postlog commented on src/login.html
> +      <div class="col-md-6 col-9 m-3 order-2 info-window simple-window">
По-умолчанию order-2 устанавливать **не нужно**

2021-07-21 17:34 UTC, Postlog commented on src/login.html
> +      <div class="col-md-3 col-9 m-3 order-1 login-window simple-window">
По-умолчанию order-1 устанавливать **не нужно**

2021-07-21 17:34 UTC, Postlog commented on src/styles/login.css
> +    .main {
Не нужно устанавливать никаких доп. стилей для main, достаточно только свойства order для info-window и login-window

2021-07-21 17:40 UTC, Mazdaywik commented
ТруЪ рабочий процесс! 👍

* @pollykon коммитит,
* @boomb0om делает замечания,
* @Gervva коммитит,
* @Postlog делает замечания.

Красиво!

2021-07-21 19:24 UTC, closed without merging

2021-07-21 19:29 UTC, Mazdaywik commented
ТруЪ рабочий процесс неожиданно прервался. @Postlog, а что так закрыли?

Если pull request закрывается, то лучше давать комментарий, почему отказались сливать ветку.

2021-07-21 19:31 UTC, Postlog commented
Мы с коммитами запутались, у нас все сломалось, поэтому решили удалить ветку и закрыть pull request